# Generated by Django 4.1.4 on 2023-02-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apptest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="description",
            field=models.TextField(default="desc", max_length=255),
            preserve_default=False,
        ),
    ]
